;/*FB_PKG_DELIM*/

__d("MWXPopover.react",["cr:2420","cr:2457","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a,c){if(b("cr:2420")!=null)return i.jsx(b("cr:2420"),babelHelpers["extends"]({},a,{ref:c}));return b("cr:2457")!=null?i.jsx(b("cr:2457"),babelHelpers["extends"]({},a,{ref:c})):null}a.displayName=a.name+" [from "+f.id+"]";c=i.forwardRef(a);g["default"]=c}),98);
__d("MAWUIThreadCache",["MAWBridgeSendAndReceive","Promise","asyncToGeneratorRuntime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=new Map();function a(a){return j.apply(this,arguments)}function j(){j=b("asyncToGeneratorRuntime").asyncToGenerator(function*(a){a=a.threadId;if(i.has(a))return(h||(h=b("Promise"))).resolve(i.get(a));var c=(yield d("MAWBridgeSendAndReceive").sendAndReceive("backend","getThreadJidByChatId",{threadId:a}));c!=null&&i.set(a,c);return c});return j.apply(this,arguments)}g.getThreadJidByChatId=a}),98);
__d("LsFalcoEventEntryPoint",[],(function(a,b,c,d,e,f){"use strict";a="message_actions";b="composer";c="icebreaker";f.messageActions=a;f.composer=b;f.icebreaker=c}),66);
__d("MWShowMessagePromptPopoverContext.react",["emptyFunction","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));e=h;d=e.createContext;var j=e.useContext,k=e.useMemo,l=e.useRef,m=d([{current:c("emptyFunction")},c("emptyFunction")]);function a(){return j(m)}function b(a){a=a.children;var b=l(c("emptyFunction")),d=k(function(){return[b,function(a){b.current=a}]},[]);return i.jsx(m.Provider,{value:d,children:a})}b.displayName=b.name+" [from "+f.id+"]";g.useMWShowMessagePromptPopoverContext=a;g.MWShowMessagePromptPopoverContextProvider=b}),98);
__d("MWDidQueryPromptsNux",[],(function(a,b,c,d,e,f){"use strict";var g=!1;function a(){g=!0}function b(){return g}f.markDidQueryPromptsNux=a;f.getDidQueryPromptsNux=b}),66);
__d("useMWLSDefaultThreadSource",["LSThreadAttributionTypeUtil","react","useLSMessagingSource"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useCallback;function a(){var a=c("useLSMessagingSource")();return i(function(b){return d("LSThreadAttributionTypeUtil").getSource(b,a)},[a])}g["default"]=a}),98);
__d("LsMessageActionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2051889");b=d("FalcoLoggerInternal").create("ls_message_action",a);e=b;g["default"]=e}),98);
__d("logMAWEditMessage",["I64","LSMessagingThreadTypeUtil","LsFalcoEventEntryPoint","LsMessageActionFalcoEvent"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a,b,e,f){if(d("LSMessagingThreadTypeUtil").isSecure(a))return;c("LsMessageActionFalcoEvent").log(function(){return{action:{type:f},error:{message:void 0},extra:{is_community_chats:d("LSMessagingThreadTypeUtil").isPublicCMThread(a)?"1":"0"},message:{attachment_type:"",entry_point:d("LsFalcoEventEntryPoint").messageActions,id:"",recipient_id:(h||(h=d("I64"))).to_string(e)},thread:{group_size:"",id:b!=null?(h||(h=d("I64"))).to_string(b):void 0,type:d("LSMessagingThreadTypeUtil").isGroup(a)?2:1}}})}g["default"]=a}),98);
__d("useIsMultiReactionEnabled",["LSMessagingThreadTypeUtil","LSThreadBitOffset","MWCMIsAnyCMThread","MWLSThread","gkx","isUnjoinedCMThread","qex"],(function(a,b,c,d,e,f,g){"use strict";b=20;function a(a){return(a=d("MWLSThread").useThread(a,function(a){if(d("isUnjoinedCMThread").isUnjoinedCMThread(a.threadType)){var b;b=a.needsAdminApprovalForNewParticipant!==!0&&((b=c("qex")._("71"))!=null?b:!1);return b&&c("gkx")("8266")}if(!d("LSThreadBitOffset").has(156,a))return!1;if(c("MWCMIsAnyCMThread")(a.threadType))return c("gkx")("8266");if(d("LSMessagingThreadTypeUtil").isDiscoverableChannel(a.threadType))return c("gkx")("10657")}))!=null?a:!1}g.MAX_REACTION_COUNT=b;g.useIsMultiReactEnabled=a}),98);
__d("MWFalcoFeatureEventLogger",["I64","LSMessagingThreadTypeUtil","MessengerWebEventsFalcoEvent","gkx"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a,b,e,f,g){c("gkx")("1471")&&c("MessengerWebEventsFalcoEvent").log(function(){return{entry_point:a,event_name:b,is_secured:d("LSMessagingThreadTypeUtil").isSecure(g),other_user_fbid:e!=null?(h||(h=d("I64"))).to_string(e):null,thread_fbid:(h||(h=d("I64"))).to_string(f)}})}g.logEvent=a}),98);
__d("getMWOtherUserFBID",["I64","LSMessagingThreadTypeUtil","ReQL","asyncToGeneratorRuntime"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a,b,c,d){return i.apply(this,arguments)}function i(){i=b("asyncToGeneratorRuntime").asyncToGenerator(function*(a,b,c,e){var f=d("LSMessagingThreadTypeUtil").isOneToOne(e);if(!f)return null;f=d("LSMessagingThreadTypeUtil").isSecure(e);if(!f)return c;e=(yield d("ReQL").firstAsync(d("ReQL").fromTableAscending(a.table("participants"),["contactId"]).getKeyRange(c).filter(function(a){a=a.contactId;return!(h||(h=d("I64"))).equal(a,b)}).take(1)));return e==null?void 0:e.contactId});return i.apply(this,arguments)}g.getMWOtherUserFBID=a}),98);
__d("useMWFalcoFeatureEventLogger",["MWFalcoFeatureEventLogger","MWPActor.react","getMWOtherUserFBID","react","useReStore"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=(i||d("react")).useCallback;function a(a,b){var e=(h||(h=c("useReStore")))(),f=d("MWPActor.react").useActor();return j(function(c,g){d("getMWOtherUserFBID").getMWOtherUserFBID(e,f,a,b).then(function(e){d("MWFalcoFeatureEventLogger").logEvent(c,g,e,a,b)})["catch"](function(){})},[e,f,a,b])}g["default"]=a}),98);
__d("MWXTooltipGroup.react",["cr:11874"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:11874")}),98);
__d("useMWXConfirmationDialog",["fbt","JSResourceForInteraction","react","useMWXLazyDialog"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=(i||d("react")).useCallback,k=c("JSResourceForInteraction")("MWXConfirmationDialog.react").__setRef("useMWXConfirmationDialog");function a(){var a=c("useMWXLazyDialog")(k),b=a[0];return j(function(a,c,d){var e=a.cancel;e=e===void 0?h._("__JHASH__ko1T7DvDF-J__JHASH__"):e;var f=a.confirm;f=f===void 0?h._("__JHASH__Yske7OqlYXF__JHASH__"):f;a=babelHelpers.objectWithoutPropertiesLoose(a,["cancel","confirm"]);b(babelHelpers["extends"]({cancel:e,confirm:f},a),function(a){return a?c():d==null?void 0:d()})},[b])}g["default"]=a}),98);
__d("useMWXPushToast",["MWXIcon.react","mwPushToast","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||c("react"),k=(h||(h=d("react"))).useCallback;function a(){return k(function(a){var b=a._isWarning_DO_NOT_USE;a=babelHelpers.objectWithoutPropertiesLoose(a,["_isWarning_DO_NOT_USE"]);d("mwPushToast").mwPushToast(babelHelpers["extends"]({},a,{icon:a.icon?{comet:j.jsx(c("MWXIcon.react"),{color:b===!0?"warning":void 0,icon:a.icon.component,size:20}),mds:a.icon.component}:void 0}))},[])}g["default"]=a}),98);
__d("useMWXPushErrorToast",["MWXIconCautionTriangle","react","useMWXPushToast"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useCallback;function a(){var a=c("useMWXPushToast")();return i(function(b){a(babelHelpers["extends"]({},b,{_isWarning_DO_NOT_USE:!0,icon:c("MWXIconCautionTriangle")}))},[a])}g["default"]=a}),98);
__d("useMWEntrypoint",["MWLSThreadDisplayContext"],(function(a,b,c,d,e,f,g){"use strict";function a(){var a=d("MWLSThreadDisplayContext").useMWLSThreadDisplayContext(),b="inbox";switch(a){case"ChatTab":b="popup_chat_box";break;case"RoomsSideChat":b="rooms_lobby";break}return b}g["default"]=a}),98);
__d("coerceMessagingThreadTypeToLSThreadType",["LSIntEnum"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a){return(h||(h=d("LSIntEnum"))).unwrapIntEnum(a)}g["default"]=a}),98);
__d("LSFetchBanners",["LSIssueNewTask"],(function(a,b,c,d,e,f){function a(){var a=arguments,c=a[a.length-1],d=[],e=[];return c.sequence([function(e){return d[0]=new c.Map(),d[0].set("thread_key",a[0]),d[1]=c.toJSON(d[0]),c.storedProcedure(b("LSIssueNewTask"),"in_thread_banner_fetch_activity_banners_queue",c.i64.cast([0,72]),d[1],void 0,void 0,c.i64.cast([0,0]),c.i64.cast([0,0]),void 0,void 0,c.i64.cast([0,0]),c.i64.cast([0,0]))},function(a){return c.resolve(e)}])}e.exports=a}),null);
__d("LSUpdateMessageSubThreadKey",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1],c=[];return b.sequence([function(c){return b.forEach(b.db.table(12).fetch([[[a[0]]],"messageId"]),function(b){var c=b.update;b.item;return c({subthreadKey:a[1]})})},function(a){return b.resolve(c)}])}e.exports=a}),null);
__d("LSUpdateOrInsertReactionV2",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1],c=[],d=[];return b.sequence([function(d){return b.db.table(226).fetch([[[a[0],a[1],a[2]]]]).next().then(function(d,e){var f=d.done;d=d.value;return f?b.db.table(12).fetch([[[a[1]]],"messageId"]).next().then(function(d,e){var c=d.done;d=d.value;return c?0:(e=d.item,b.sequence([function(c){return b.forEach(b.filter(b.db.table(226).fetch([[[a[0],a[1],a[2]]]]),function(c){return b.i64.eq(c.threadKey,a[0])&&c.messageId===a[1]&&b.i64.eq(c.reactionFbid,a[2])&&b.i64.lt(c.authorityLevel,a[5])}),function(a){return a["delete"]()})},function(c){return b.db.table(226).add({messageId:a[1],threadKey:a[0],reactionFbid:a[2],messageTimestamp:e.timestampMs,authorityLevel:a[5],count:a[4],viewerIsReactor:a[6],viewerReactionTimestampMs:a[7],lastUpdatedTimestampMs:a[8]})}]))}):(e=d.item,c[2]=e.lastUpdatedTimestampMs,c[1]=e.authorityLevel,b.i64.eq(a[5],b.i64.cast([0,20]))||b.i64.eq(c[1],b.i64.cast([0,80]))&&b.i64.eq(a[5],b.i64.cast([0,80]))||b.i64.eq(c[1],b.i64.cast([0,20]))&&b.i64.eq(a[5],b.i64.cast([0,80]))&&b.i64.le(b.i64.add(c[2],b.i64.cast([0,2e3])),a[8])||b.i64.eq(c[1],b.i64.cast([0,20]))&&b.i64.eq(a[5],b.i64.cast([0,60]))||b.i64.eq(c[1],b.i64.cast([0,60]))&&b.i64.eq(a[5],b.i64.cast([0,80]))&&b.i64.le(c[2],a[8])?c[3]=!0:c[3]=!1,c[3]?b.db.table(226).put({messageId:a[1],threadKey:a[0],reactionFbid:a[2],messageTimestamp:e.messageTimestamp,reactionLiteral:a[3],count:a[4],authorityLevel:a[5],viewerIsReactor:a[6],viewerReactionTimestampMs:b.i64.cast([0,0]),lastUpdatedTimestampMs:a[8]}):b.resolve())})},function(a){return b.resolve(d)}])}e.exports=a}),null);
__d("MWXIconFaceHappyOutline",["MWXSvgIcon","SVGIcon","cr:6724","gkx"],(function(a,b,c,d,e,f,g){"use strict";a=d("MWXSvgIcon").mwxSvgIcon(d("SVGIcon").svgIcon(b("cr:6724")),c("gkx")("571"));g["default"]=a}),98);